spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://192.168.25.5:5432/rabbitmq-pubsub
      username: postgres
      password: root97
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
