spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/rabbitmq_pubsub
      maximumPoolSize: 20
      username: postgres
      password: qq@33ML
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
